// ==========================================
// js/main.js (メインエントリーポイント・グローバル公開バインド)
// ==========================================

import {
    API_URL,
    RARITY_CAPS,
    EVO_COST_XP,
    EVO_STOCK_REQ,
    REBORN_COST_XP,
    RARITY_ORDER,
    SKILL_TYPES,
    LV_BONUS_RATE,
    EXP_REQ,
    MAT_EXP,
    SELL_PRICES,
    LOGIN_BONUS_EXP,
    MAX_ITEM_LEVEL,
    MASTER_COUNT,
    TITLES,
    MISSIONS,
    MISSION_ALL_CLEAR,
    ROGUE_TILES,
    GUIDE_DATA,
    rawData,
    playData,
    gameState,
    dailyMissions,
    rogueData,
    runtimeState,
    initUserId,
    loadSaveData,
    saveGame
} from './state.js?v=9.3.6';

import {
    getRarityIndex,
    getDisplayName,
    getGradeMultiplier,
    generateCalcQuestion,
    drawRadarChart,
    audioCtx,
    toggleMute,
    playSE,
    playBGM,
    stopBGM,
    playMmlBGM,
    BGM_MML
} from './utils.js?v=9.3.6';

import {
    uploadData,
    downloadData,
    fetchData
} from './api.js?v=9.3.6';

import {
    showCutIn,
    updateUI,
    togglePause,
    resumeGame,
    retryGame,
    backToTitleFromPause,
    startCountdown,
    startTimer,
    getCharaStats,
    finishGame,
    handleResultClose,
    backToTitle
} from './battle-core.js?v=9.3.6';

import {
    startNormalGameCheck,
    startGame,
    nextQuestion,
    judge,
    goToOathMenuCheck,
    goToReliefMenuCheck,
    goToOathMenuSurvivalCheck,
    goToReliefMenuSurvivalCheck,
    startSurvivalGame,
    startRandomGameCheck,
    goToOathMenuRandomCheck,
    goToReliefMenuRandomCheck,
    startRandomGame,
    startTypingGameCheck,
    goToOathMenuTypingCheck,
    goToReliefMenuTypingCheck,
    startTypingGame,
    nextTypingQuestion,
    renderTypingRomaji,
    handleTypingInput,
    startCalcGame,
    renderCalcInput,
    renderCalcProgress,
    handleCalcButton,
    submitCalcAnswer,
    nextCalcQuestion,
    startCalcTimer,
    startRevengeMode,
    toggleOath,
    toggleRelief,
    startOathGame,
    startReliefGame
} from './quest-normal.js?v=9.3.6';

import {
    addRogueLog,
    renderRogueLogs,
    startRogueMode,
    generateRogueFloor,
    drawRogueMap,
    moveRoguePlayer,
    triggerRogueRNGEvent,
    processRogueTile,
    triggerRogueShop,
    closeRogueShop,
    renderRogueShopContents,
    buyRogueHeal,
    buyRogueAtk,
    buyRogueSteps,
    getRogueEnemyChar,
    triggerRogueBattle,
    showRogueCutIn,
    updateRogueUI,
    escapeRogueConfirm,
    exitRogueSystem
} from './quest-explore.js?v=9.3.6';

import {
    openGacha,
    closeGacha,
    rollGacha,
    rollGuaranteedTenGacha,
    executeGacha,
    showGachaResult,
    closeGachaResult,
    renderZukan,
    changeZukanSort,
    openCharaDetail,
    closeCharaDetail,
    equipCurrentChara,
    useExpItem,
    executeEvolution,
    executeReincarnation,
    openEnhanceMenu,
    closeEnhanceMenu,
    renderEnhanceList,
    toggleMaterial,
    getNeededExpForMax,
    getSelectedTotalExp,
    updateEnhancePreview,
    executeBulkEnhance,
    sellCharaStock,
    openShop,
    closeShop,
    renderShop,
    buyItem,
    exchangeBook,
    openMissions,
    closeMissions,
    renderMissions,
    claimMission,
    claimAllClear,
    updateMissionProgress,
    updateMissionBadge,
    openTitles,
    closeTitles,
    renderTitles,
    claimTitle,
    checkTitles,
    checkLoginBonus,
    closeLoginBonus,
    checkMissionDate
} from './gacha-shop.js?v=9.3.6';

import {
    initTitle,
    filterSubjects,
    filterUnits,
    updateTitleInfo,
    updateCategoryBadges,
    openCategory,
    closeCategory,
    closeAllCategoryModals,
    hideCurrentCategoryOverlay,
    returnToCurrentCategory,
    openUnitSelection,
    closeUnitSelection,
    openRandomMenu,
    closeRandomMenu,
    openTypingMenu,
    closeTypingMenu,
    openSurvivalMenu,
    closeSurvivalMenu,
    openCalcMenu,
    closeCalcMenu,
    openRogueMenu,
    closeRogueMenu,
    openOathMenu,
    closeOathMenu,
    openReliefMenu,
    closeReliefMenu,
    openSyncMenu,
    closeSyncMenu,
    openVersionHistory,
    closeVersionHistory,
    openGiftMenu,
    closeGiftMenu,
    renderGiftList,
    receiveAllGifts,
    checkAdminGifts,
    openRecord,
    closeRecord,
    renderRecord,
    addCalcRecord,
    showAppModal,
    showAlert,
    showConfirm,
    GuideModule
} from './ui-manager.js?v=9.3.6';

import {
    openTeamBattleSetup,
    closeTeamBattleSetup,
    openPartyFormation,
    closePartyFormation,
    savePartyFormation,
    selectPartySlot,
    setPartyMember,
    removePartyMember,
    renderPartyFormation,
    updateTeamBattleSetupPreview,
    initTbGradeSelect,
    filterTbSubjects,
    filterTbUnits,
    tbState,
    getTbCharaStats,
    calcTbMaxHp,
    getTbAffinityMultiplier,
    getTbAffinityInfo,
    calcTbTickDamage,
    startTeamBattle,
    tbGameLoop,
    nextTbQuestion,
    judgeTbAnswer,
    switchTbActiveChar,
    updateTbBattleUI,
    escapeTeamBattle,
    finishTeamBattle,
    toggleTbPause,
    resumeTbGame,
    escapeTeamBattleFromPause
} from './special-quest/special-quest-engine.js?v=9.3.6';

// ==========================================
// インライン onclick / 動的UI互換用 window 一括バインド
// ==========================================
const globalScope = typeof window !== 'undefined' ? window : globalThis;
Object.assign(globalScope, {
    // 状態・定数
    API_URL,
    RARITY_CAPS,
    EVO_COST_XP,
    EVO_STOCK_REQ,
    REBORN_COST_XP,
    RARITY_ORDER,
    SKILL_TYPES,
    LV_BONUS_RATE,
    EXP_REQ,
    MAT_EXP,
    SELL_PRICES,
    LOGIN_BONUS_EXP,
    MAX_ITEM_LEVEL,
    MASTER_COUNT,
    TITLES,
    MISSIONS,
    MISSION_ALL_CLEAR,
    ROGUE_TILES,
    GUIDE_DATA,
    rawData,
    playData,
    gameState,
    dailyMissions,
    rogueData,
    runtimeState,
    initUserId,
    loadSaveData,
    saveGame,

    // ユーティリティ・音響
    getRarityIndex,
    getDisplayName,
    getGradeMultiplier,
    generateCalcQuestion,
    drawRadarChart,
    audioCtx,
    toggleMute,
    playSE,
    playBGM,
    stopBGM,
    playMmlBGM,
    BGM_MML,

    // 通信
    uploadData,
    downloadData,
    fetchData,

    // バトルコア
    showCutIn,
    updateUI,
    togglePause,
    resumeGame,
    retryGame,
    backToTitleFromPause,
    startCountdown,
    startTimer,
    getCharaStats,
    finishGame,
    handleResultClose,
    backToTitle,

    // 通常・サバイバル・計算・タイピング・誓約・救済
    startNormalGameCheck,
    startGame,
    nextQuestion,
    judge,
    goToOathMenuCheck,
    goToReliefMenuCheck,
    goToOathMenuSurvivalCheck,
    goToReliefMenuSurvivalCheck,
    startSurvivalGame,
    startRandomGameCheck,
    goToOathMenuRandomCheck,
    goToReliefMenuRandomCheck,
    startRandomGame,
    startTypingGameCheck,
    goToOathMenuTypingCheck,
    goToReliefMenuTypingCheck,
    startTypingGame,
    nextTypingQuestion,
    renderTypingRomaji,
    handleTypingInput,
    startCalcGame,
    renderCalcInput,
    renderCalcProgress,
    handleCalcButton,
    submitCalcAnswer,
    nextCalcQuestion,
    startCalcTimer,
    startRevengeMode,
    toggleOath,
    toggleRelief,
    startOathGame,
    startReliefGame,

    // 探索
    addRogueLog,
    renderRogueLogs,
    startRogueMode,
    generateRogueFloor,
    drawRogueMap,
    moveRoguePlayer,
    triggerRogueRNGEvent,
    processRogueTile,
    triggerRogueShop,
    closeRogueShop,
    renderRogueShopContents,
    buyRogueHeal,
    buyRogueAtk,
    buyRogueSteps,
    getRogueEnemyChar,
    triggerRogueBattle,
    showRogueCutIn,
    updateRogueUI,
    escapeRogueConfirm,
    exitRogueSystem,

    // ガチャ・図鑑・育成・ショップ・実績
    openGacha,
    closeGacha,
    rollGacha,
    rollGuaranteedTenGacha,
    executeGacha,
    showGachaResult,
    closeGachaResult,
    renderZukan,
    changeZukanSort,
    openCharaDetail,
    closeCharaDetail,
    equipCurrentChara,
    useExpItem,
    executeEvolution,
    executeReincarnation,
    openEnhanceMenu,
    closeEnhanceMenu,
    renderEnhanceList,
    toggleMaterial,
    getNeededExpForMax,
    getSelectedTotalExp,
    updateEnhancePreview,
    executeBulkEnhance,
    sellCharaStock,
    openShop,
    closeShop,
    renderShop,
    buyItem,
    buyShopItem: buyItem,
    exchangeBook,
    openMissions,
    closeMissions,
    renderMissions,
    claimMission,
    claimAllClear,
    updateMissionProgress,
    updateMissionBadge,
    openTitles,
    closeTitles,
    renderTitles,
    claimTitle,
    checkTitles,
    checkLoginBonus,
    closeLoginBonus,
    checkMissionDate,

    // UIマネージャー・モーダル・ガイド
    initTitle,
    filterSubjects,
    filterUnits,
    updateTitleInfo,
    updateCategoryBadges,
    openCategory,
    closeCategory,
    closeAllCategoryModals,
    hideCurrentCategoryOverlay,
    returnToCurrentCategory,
    openUnitSelection,
    closeUnitSelection,
    openRandomMenu,
    closeRandomMenu,
    openTypingMenu,
    closeTypingMenu,
    openSurvivalMenu,
    closeSurvivalMenu,
    openCalcMenu,
    closeCalcMenu,
    openRogueMenu,
    closeRogueMenu,
    openOathMenu,
    closeOathMenu,
    openReliefMenu,
    closeReliefMenu,
    openSyncMenu,
    closeSyncMenu,
    openVersionHistory,
    closeVersionHistory,
    openGiftMenu,
    closeGiftMenu,
    renderGiftList,
    receiveAllGifts,
    checkAdminGifts,
    openRecord,
    closeRecord,
    renderRecord,
    addCalcRecord,
    showAppModal,
    showAlert,
    showConfirm,
    GuideModule,
    
    // チームバトルクエスト関連
    openTeamBattleSetup,
    closeTeamBattleSetup,
    openPartyFormation,
    closePartyFormation,
    savePartyFormation,
    selectPartySlot,
    setPartyMember,
    removePartyMember,
    renderPartyFormation,
    updateTeamBattleSetupPreview,
    initTbGradeSelect,
    filterTbSubjects,
    filterTbUnits,
    tbState,
    getTbCharaStats,
    calcTbMaxHp,
    getTbAffinityMultiplier,
    getTbAffinityInfo,
    calcTbTickDamage,
    startTeamBattle,
    tbGameLoop,
    nextTbQuestion,
    judgeTbAnswer,
    switchTbActiveChar,
    updateTbBattleUI,
    escapeTeamBattle,
    finishTeamBattle,
    toggleTbPause,
    resumeTbGame,
    escapeTeamBattleFromPause
});

// ==========================================
// 初期化エントリーポイント
// ==========================================
let isAppInitialized = false;
async function initApp() {
    if (isAppInitialized) return;
    isAppInitialized = true;
    initUserId();
    loadSaveData();
    checkMissionDate();
    await fetchData();
    initTitle();
    checkLoginBonus();
}

if (typeof window !== 'undefined') {
    if (document.readyState === 'complete' || document.readyState === 'interactive') {
        initApp();
    } else {
        document.addEventListener('DOMContentLoaded', initApp);
        window.addEventListener('load', initApp, { once: true });
    }
}
